name: Build

on:
  pull_request:
    branches: [master, hdoc-2.0]
  push:
    branches: [master, hdoc-2.0]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build
        run: |
          zig build install

      - name: Test
        run: |
          zig build test
